# Generated by Django 5.2.17 on 2026-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='underlying_conditions',
            field=models.TextField(blank=True),
        ),
    ]
