# Generated by Django 5.2.17 on 2026-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientconnection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('BLOCKED', 'Đã chặn')], default='PENDING', max_length=20),
        ),
    ]
