# Generated by Django 5.2.17 on 2026-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorpatientconnection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
