# Generated by Django 5.2.17 on 2026-09-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='care_notifi_recipie_75af2a_idx',
            old_name='care_notifi_recipie_6d9a42_idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Nghiêm trọng')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Mở'), ('ACKNOWLEDGED', 'Đã ghi nhận'), ('RESOLVED', 'Đã xử lý')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10),
        ),
    ]
