# Generated by Django 5.2.17 on 2026-09-10 02:55

import care.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_vitalsign_weight_glucose'),
        ('doctors', '0002_alter_doctorpatientconnection_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='P2PMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=care.models.chat_attachment_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=care.models.patient_file_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='care_appoin_patient_92a3eb_idx',
            old_name='care_appoin_patient_8e1a10_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='care_appoin_doctor__5deec9_idx',
            old_name='care_appoin_doctor_5f2a2e_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='care_appoin_status_dbfbe8_idx',
            old_name='care_appoin_status_0f1f80_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationlog',
            new_name='care_medica_schedul_29063e_idx',
            old_name='care_medica_schedule_b2e60d_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationschedule',
            new_name='care_medica_patient_5333e9_idx',
            old_name='care_medica_patient_1c38ec_idx',
        ),
        migrations.RenameIndex(
            model_name='medicationschedule',
            new_name='care_medica_start_d_048f3b_idx',
            old_name='care_medica_start_d6c85c_idx',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='connection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='doctors.doctorpatientconnection'),
        ),
        migrations.AddField(
            model_name='p2pmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='care.chatroom'),
        ),
        migrations.AddField(
            model_name='p2pmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['active', 'updated_at'], name='care_chatro_active_df2e37_idx'),
        ),
        migrations.AddIndex(
            model_name='p2pmessage',
            index=models.Index(fields=['room', 'created_at'], name='care_p2pmes_room_id_429408_idx'),
        ),
        migrations.AddIndex(
            model_name='patientfile',
            index=models.Index(fields=['patient', 'uploaded_at'], name='care_patien_patient_0b645d_idx'),
        ),
    ]
