# Generated by Django 5.2.17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.deletion
import django.db.models.deletion
from django.conf import settings


def backfill_patient_targets(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    ChatConversation = apps.get_model('chatbot', 'ChatConversation')
    patient_ids = set(User.objects.filter(role='PATIENT').values_list('id', flat=True))
    ChatConversation.objects.filter(user_id__in=patient_ids, target_patient__isnull=True).update(
        target_patient_id=models.F('user_id')
    )


def reverse_backfill(apps, schema_editor):
    apps.get_model('chatbot', 'ChatConversation').update(target_patient=None)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_alter_patientprofile_avatar_url'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='target_patient',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='chatbot_target_conversations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='context_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'target_patient', 'updated_at'], name='chatbot_conv_scope_idx'),
        ),
        migrations.RunPython(backfill_patient_targets, reverse_backfill),
    ]
